### ISSUE TITLE
希望增加一个隔开笔记本的样式

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_doctree_compress#8]
```css
/* 笔记本区隔 CSS片段*/
.sy__file ul.b3-list.b3-list--background {
    border-radius: 0.3em;
    margin: 6px 10px 6px 12px;
    outline: 1.5px double #8e9ba3;
    overflow: hidden;
}
```

用起来效果大概是这样：

![image](https://github.com/zxkmm/siyuan_doctree_compress/assets/78434827/07ba9b69-cce5-4102-80e3-d5bb49cf86c9)
